WITH LATEST_CONSENT AS (
    SELECT *
    FROM (
        SELECT 
            c.*,
            ROW_NUMBER() OVER (
                PARTITION BY c.player_id, c.product_type, c.channel_type
                ORDER BY c.MARKETING_CONSENT_UPDATED_AT DESC
            ) AS rn
        FROM DW_WAREHOUSE.PUBLIC.GGCORE_PLAYER_MARKETING_AGREEMENT c
        WHERE 
            c.CHANNEL_TYPE = 'Email'
            AND c.PRODUCT_TYPE = 'Casino'
    )
    WHERE rn = 1
)
,LATEST_GAME_LIMIT AS (
    SELECT *
    FROM DW_WAREHOUSE.PUBLIC.GGCORE_PLAYER_RESPONSIBLE_GAMING_GAME_LIMIT
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY GP_ID
        ORDER BY UPDATEDAT DESC
    ) = 1
)
,LATEST_ACCOUNT AS (
    SELECT *
    FROM DW_WAREHOUSE.PUBLIC.GP_ACCOUNT
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY GP_ID
        ORDER BY UPDATED_AT DESC
    ) = 1
)
,LATEST_ACCOUNT_STATUS AS (
    SELECT *
    FROM DW_WAREHOUSE.PUBLIC.GP_ACCOUNT_STATUS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY GP_ID
        ORDER BY UPDATED_AT DESC
    ) = 1
)
,LATEST_WALLET AS (
    SELECT *
    FROM DW_WAREHOUSE.PUBLIC.GGCORE_WALLET
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACCOUNT_ID
        ORDER BY UPDATED_AT DESC
    ) = 1
)


,CONSENTED_PLAYERS AS (
    SELECT DISTINCT p.gpid
    FROM DW_WAREHOUSE.PUBLIC.GGCORE_DISTINCT_PLAYER AS p
    
    JOIN LATEST_CONSENT AS c
        ON p.id = c.player_id AND P.BRANDID = C.BRAND_ID
    
    LEFT JOIN LATEST_GAME_LIMIT l
        ON l.GP_ID = p.gpid AND L.BRANDID = P.BRANDID
        
    LEFT JOIN LATEST_ACCOUNT a
        ON a.GP_ID = p.gpid AND A.BRAND_ID = P.BRANDID
        
    LEFT JOIN LATEST_ACCOUNT_STATUS s
        ON s.GP_ID = p.gpid AND S.BRAND_ID = P.BRANDID
        
    LEFT JOIN LATEST_WALLET w
        ON w.ACCOUNT_ID = p.ACCOUNTID AND W.BRAND_ID = P.BRANDID
    
    WHERE
        c.CHANNEL_TYPE = 'Email'
        AND c.PRODUCT_TYPE = 'Casino'
        AND c.IS_MARKETING_CONSENT = TRUE
        
        AND COALESCE(l.CASINO, FALSE) = FALSE
        AND COALESCE(l.SLOT, FALSE) = FALSE
        AND COALESCE(l.LIVEDEALER, FALSE) = FALSE
        
        AND COALESCE(a.IS_SELF_EXCLUDED, FALSE) = FALSE
        AND COALESCE(a.IS_PROMOTION_ENABLED, TRUE) = TRUE
        
        AND s.STATUS = 'ACTIVE'
        
        AND w.IS_ACTIVE = TRUE
)



,GAME_RTP AS (
    SELECT GAME_CODE, GAME_RTP
    FROM (
        SELECT 
            GAME_CODE, 
            GAME_RTP,
            ROW_NUMBER() OVER (PARTITION BY GAME_CODE ORDER BY UPDATED_AT DESC) AS rn
        FROM DW_WAREHOUSE.PUBLIC.CP_STATS_PERIODIC_DAILY
    )
    WHERE rn = 1
)

-- Top Category is now calculated on the FULL window (2025-01-01 to Present)
,top_category AS (
    SELECT *
    FROM (
        SELECT 
            GP_ID,
            CATEGORY_ID,
            SUM(BET) AS total_bet,
            ROW_NUMBER() OVER (PARTITION BY GP_ID ORDER BY SUM(BET) DESC) AS rn
        FROM DW_WAREHOUSE.PUBLIC.GP_STATISTICS_GAME_CASINO
        WHERE AGGREGATED_AT >= '2025-01-01' 
        AND SITE_ID IN ('GGPUKE', 'EVPUKE', 'Natural8', 'GGPOK', 'GGPJP', 'GGPUA', 'GGPCOM', 'GGPUK', 'GGPEU', 'GGPFI', 'GGPHU', 'GGPPL')
        GROUP BY GP_ID, CATEGORY_ID
    ) ranked
    WHERE rn = 1
)

-- Single GPID (user id) check on the FULL window
,SINGLE_GPID_USERS AS (
    SELECT 
        NICKNAME
    FROM DW_WAREHOUSE.PUBLIC.GP_STATISTICS_GAME_CASINO
    WHERE AGGREGATED_AT >= '2025-01-01' 
    GROUP BY 
        NICKNAME
    HAVING 
        COUNT(DISTINCT GP_ID) = 1 
)

,LATEST_INFO AS (
  SELECT
    GGPASS_ID,
    GP_ID,
    NICKNAME,
    BRAND_ID,
    SITE_ID
  FROM (
    SELECT
      GGPASS_ID,
      GP_ID,
      NICKNAME,
      BRAND_ID,
      SITE_ID,
      AGGREGATED_AT,
      ROW_NUMBER() OVER (PARTITION BY GP_ID ORDER BY AGGREGATED_AT DESC) AS rn
    FROM DW_WAREHOUSE.PUBLIC.GP_STATISTICS_GAME_CASINO
    WHERE AGGREGATED_AT >= '2025-01-01'
  ) latest
  WHERE rn = 1
)

SELECT 
    DATE_TRUNC('WEEK', GC.AGGREGATED_AT) AS GAME_WEEK,
    GC.GGPASS_ID,
    REPLACE(GC.GGPASS_ID, '-', '') AS CID,
    LN.NICKNAME, 
    LN.BRAND_ID,
    LN.SITE_ID,
    TC.CATEGORY_ID AS TOP_CATEGORY,
    
    SUM(GC.BET) AS BET,
    SUM(GC.GGR) AS GGR,
    SUM(GC.BET * (1 - COALESCE(R.GAME_RTP, 0.96))) AS THEO_WIN, 
    COUNT(DISTINCT GC.AGGREGATED_AT) AS DAYS_PLAYED
    
FROM 
    DW_WAREHOUSE.PUBLIC.GP_STATISTICS_GAME_CASINO AS GC

-- Joins
JOIN CONSENTED_PLAYERS AS C ON C.GPID = GC.GP_ID
JOIN SINGLE_GPID_USERS AS SGU ON SGU.NICKNAME = GC.NICKNAME
LEFT JOIN GAME_RTP AS R ON R.GAME_CODE = GC.GAME_TYPE
LEFT JOIN TOP_CATEGORY AS TC ON TC.GP_ID = GC.GP_ID
LEFT JOIN LATEST_INFO AS LN ON LN.GP_ID = GC.GP_ID
    
WHERE 
    GC.AGGREGATED_AT >= '2025-12-01' 
    
    AND gc.site_id IN ('GGPUKE', 'EVPUKE', 'Natural8', 'GGPOK', 'GGPJP', 'GGPUA', 'GGPCOM', 'GGPUK', 'GGPEU', 'GGPFI', 'GGPHU', 'GGPPL')
    AND GC.GENERAL_GAME_TYPE = 'JDBGAMING'

    
GROUP BY 
    DATE_TRUNC('WEEK', GC.AGGREGATED_AT),
    GC.GGPASS_ID,
    LN.NICKNAME,
    LN.SITE_ID,
    LN.BRAND_ID,
    TC.CATEGORY_ID

HAVING 
    SUM(GC.BET) > 0 AND COUNT(DISTINCT GC.AGGREGATED_AT) > 0;

